version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 20
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - echo Docker Build
      - docker build -t 523530166249.dkr.ecr.ap-northeast-1.amazonaws.com/mynavi-sample-ecs-bff:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo ECR Docker Push
      - aws ecr get-login-password | docker login --username AWS --password-stdin 523530166249.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker push 523530166249.dkr.ecr.ap-northeast-1.amazonaws.com/mynavi-sample-ecs-bff:latest      
artifacts:
  files:
    - target/mynavi-sample-aws-ecs-backend-for-frontend-*.jar

cache:
  paths:
    - '/root/.m2/**/*'    