spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
server:
  servlet:
    context-path: /backend-for-frontend
service:
  dns: http://internal-Demo-PrivateALB-1366503673.ap-northeast-1.elb.amazonaws.com