spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
    credentials:
      profileName:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1
server:
  servlet:
    context-path: /backend-for-frontend
service:  
  dns: http://internal-Demo-PrivateALB-2060768951.ap-northeast-1.elb.amazonaws.com 
  